### ISSUE TITLE
`derive` does not work with generic parameters.

### ISSUE THREAD

**Issue by sgrif** [argonaut-io/argonaut#174]
Our API is consistently wrapping all results in a `data` top level key. I had attempted to represent that in the type like so:

``` scala
import argonaut._, Argonaut._

case class ResponseBody[A](data: A)

object ResponseBody {
  implicit def jsonEncode[A: EncodeJson]: EncodeJson[ResponseBody[A]] =
    EncodeJson.derive[ResponseBody[A]]

  implicit def jsonDecode[A: DecodeJson]: DecodeJson[ResponseBody[A]] =
    DecodeJson.derive[ResponseBody[A]]
}
```

However, it appears that the macro invocation assumes no type parameters.

**Comment by seanparsons** [comment]
What version is this with?

**Comment by sgrif** [comment]
6.1-M5

**Comment by sgrif** [comment]
Oh and here's the specific error if it helps:

```
type mismatch;
 found   : toEncode.data.type (with underlying type A)
 required: A
  implicit def jsonEncode[A: EncodeJson]: EncodeJson[ResponseBody[A]] = EncodeJson.derive[ResponseBody[A]]
```

**Comment by seanparsons** [comment]
Hmmm, that sounds frustrating, it should be fine that you're supplying the type parameters to those methods. It looks like we end up constructing code that doesn't compile as a result of the macro (the "toEncode" bit is the big clue), which is what the compiler is actually complaining about, it just places that at the point of the invocation of the macro because that's the best it can do.

I'll have to compare some generic and non-generic examples to see why exactly it's being an idiot however.

**Comment by sgrif** [comment]
Yeah, I think it should be as simple as checking if the supplied type takes type arguments, and if so adding them to the resulting quasi-quote. I'd submit a patch, but I wanted to document the issue somewhere before I forgot.

**Comment by jdrphillips** [comment]
Any update on this?

**Comment by seanparsons** [comment]
@jdrphillips I haven't looked into it in anymore detail, but no-one has been particularly screaming out loud for it either.

**Comment by adelbertc** [comment]
@jdrphillips @sgrif Could you use https://github.com/alexarchambault/argonaut-shapeless ?
