### ISSUE TITLE
6.1.x keep binary compatibility?

### ISSUE THREAD

**Issue by xuwei-k** [argonaut-io/argonaut#176]
if so, I think we should
- [x] create `series/6.1.x` branch
- [x] add migration-manager settings for `series/6.1.x` branch
- [x] organize https://github.com/argonaut-io/argonaut/issues/118

**Comment by seanparsons** [comment]
Yup, I'd definitely like to do this, the mima stuff has been commented out in the build file for a bit so that should be easy to get in.

As far as #118 I'd like to cherry pick stuff that's really important and bin off the rest, otherwise we'll just have a bazillion open issues with every single last feature everyone ever wanted hanging around.

**Comment by xuwei-k** [comment]
created `series/6.1.x` branch https://github.com/argonaut-io/argonaut/commit/4b4ee3d33bf327d5ae61cb9fa8
