### ISSUE TITLE
Loss of scale when decoding numbers

### ISSUE THREAD

**Issue by carymrobbins** [argonaut-io/argonaut#205]
When we decode numbers, we lose the scale -

```scala
argonaut.Parse.parse("2.00")
// scalaz.\/[String,argonaut.Json] = \/-(2)
```

Compare this to Play's JSON library -

```scala
play.api.libs.json.Json.parse("2.00")
// play.api.libs.json.JsValue = 2.00
```

While in most cases this is fine, in others we actually need this information.  For instance, if we're consuming an AST encoded in JSON, we can infer the type of this value to be `Double`.  However, the current implementation prevents this and we'd just end up inferring `Int`.

I use Play as an example since it may present a possible solution.  Instead of parsing the value as `Double` it could be parsed as `scala.math.BigDecimal` (which is the underlying type of Play's `JsNumber`).  We could then do what we wish from there - inspect the scale, convert to `Int`, `Double`, etc.

Does this sound reasonable?  If so, I'd be willing to work on a PR for this.

**Comment by carymrobbins** [comment]
This seems related, although it's not clear to me what the resolution was - https://github.com/argonaut-io/argonaut/issues/98

**Comment by seanparsons** [comment]
So this is totally by design and most JSON libraries actually do something weird for no real reason other than the rest do it.

If you're using 6.1 then the support for arbitrary decimal numbers is in there and it's giving you the right thing, as the spec of more recent times specifies numbers of arbitrary precision. Originally they were double precision floats, because JavaScript.

If Play is using BigDecimal then they actually support less possible numbers than Argonaut does (see here: https://github.com/argonaut-io/argonaut/blob/0a3944beff654b493acc80ffc4cee414e3130ffd/argonaut/src/main/scala/argonaut/JsonNumber.scala#L199-L205).

Certainly as the JSON specs (all of them) stand there's no support for treating numbers in a different way, depending on if they include a decimal point or not. Argonaut takes the viewpoint that regardless of how the number is represented you should be able to ask for the representation you want., so for example decoding "2.00" into an Int.

**Comment by carymrobbins** [comment]
Actually, I just built master from source and it seems it _does_ provide this feature already.

```scala
scala> Parse.parse("2").right.get.number.get.toBigDecimal.scale
res14: Int = 0

scala> Parse.parse("2.0").right.get.number.get.toBigDecimal.scale
res15: Int = 1

scala> Parse.parse("2.00").right.get.number.get.toBigDecimal.scale
res16: Int = 2
```

Although, it seems like some other things have changed as well, like the use of `Either` instead of `\/`.

Any idea when we'll see a release with this feature?

**Comment by seanparsons** [comment]
@carymrobbins You appear to have just ignored my entire response above, 6.1 has this functionality already...

**Comment by carymrobbins** [comment]
@seanparsons - I certainly didn't try to ignore your response, seems like my interpretation wasn't quite correct.  If you are saying that 6.1 has it, then I'm good.  (Even at that, since master has it, I'm good even with that.)

Right now, it seems that 6.1 is causing dependency issues with specs2, but 6.2-SNAPSHOT doesn't, so I may just experiment with that for now.

Note that the http://argonaut.io/ page still shows 6.0.4 as the latest stable and 6.1-M4 as the latest, so that caused a little confusion as well.

**Comment by seanparsons** [comment]
@carymrobbins Yes, apologies for the website still being out of date, it's on my list, just been a bit slammed with life at the moment! :)
