### ISSUE TITLE
scalajs

### ISSUE THREAD

**Issue by i-am-the-slime** [argonaut-io/argonaut#259]
Is there scalajs support for argonaut? I'd like to avoid using circe 💃

**Comment by seanparsons** [comment]
I've not had the time to investigate it, I'd be happy to assist any efforts on that front though.

**Comment by xuwei-k** [comment]
We should replace testing library because specs2 does not support scala.js https://github.com/etorreborre/specs2/issues/465

**Comment by rhyskeepence** [comment]
We use an internally published sjs fork of argonaut, which allows us to share data types and codecs between the client and server. As Kenji said, the tests do not run against the sjs target, but it is possible to cross compile.

I recently tried switching to circe, but it resulted in an extra 2mb in our fast-opt js file (because of the extra dependency on cats) and our full compile time increased by about a minute (I switched to semiauto derivation of codecs rather than hand crafted codecs).

I'd like to assist to make it a first class thing. In addition to the testing library replacement, it would be nice if the parser used scala.scalajs.js.JSON too.

**Comment by seanparsons** [comment]
I'd be happy to have it compiling for Scala.js but not testing there, something is better than nothing in my mind and in theory if we're rocking the same code we're still getting the test coverage.

@rhyskeepence Are you able to PR whatever changes are necessary for that to work from your fork?

**Comment by alonsodomin** [comment]
any chance of getting the ScalaJS artifacts published in Maven Central?

**Comment by xuwei-k** [comment]
6.2 released http://repo1.maven.org/maven2/io/argonaut/argonaut_sjs0.6_2.12/
